### ISSUE TITLE
Rincheat se error

### ISSUE THREAD

**Issue by yushinyuma** [Rinnegatamante/rinCheat#51]
An error occurred:
[string “?”]:440: attempt to get length of a nil value (local ‘test_dir’) .when i click x on my savedata game.. I saw the other users comment too they same error how fix this?

**Comment by Rinnegatamante** [comment]
Directly from Wololo's topic:
"Use first slots for savedatas for now, this should solve the issue. I'm going to push a critical bugfix version to gekihen for this error and another one i encountered both right after release. "

The hotfix has already been pushed to GekiHen, but still not approved by admins.

**Comment by yushinyuma** [comment]
I already did that but same result. Waiting for next update eheh..

**Comment by Rinnegatamante** [comment]
The hotfix is available, let me know if it fix your issues: http://gekihen.customprotocol.com/en/project/rinCheat-SE

**Comment by zephiel1802** [comment]
@Rinnegatamante i tried to connect to genkihen but always give me 503 service unavailable. is there any other way that i can access to the hotfix?

**Comment by Rinnegatamante** [comment]
http://rinnegatamante.it/rinCheatSE_bugfix.vpk

**Comment by Rinnegatamante** [comment]
Closing this since the author had not answered to my request. Assuming issue is fixed now.

**Comment by p16774** [comment]
I can confirm this does NOT fix the issue. If I have a save with more slots saved than just the first available slot ingame I get this error. Once I remove the savedata the app opens fine (though it says there's no savedata)
